services:
  jenkins:
    container_name: jenkins
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    user: "0"
    ports:
      - "8085:8080"
      - "50000:50000"
    volumes:
      - ~/.jenkins_home:/var/jenkins_home
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - inet

networks:
  inet:
    external: true
